### ISSUE TITLE
Is Convexity.Unknown equivalent to nonconvex?

### ISSUE THREAD

**Issue by ZedongPeng** [cog-imperial/suspect#9]
Given a model, I want to identify each constraint's convexity. In the suspect package, there are four statuses related to Convexity, Convexity.Convex, Convexity.Linear, Convexity.Concave, Convexity.Unknown. I am wondering if Convexity.Unknown means nonconvex?

Thanks.

**Comment by fracek** [comment]
Convexity.Unknown means that SUSPECT was not able to prove that the function is Convex/Concave/Linear. Usually this is because 1) the function is non convex or 2) the function is convex but cannot be proven convex with SUSPECT rule based engine.

**Comment by ZedongPeng** [comment]
> Convexity.Unknown means that SUSPECT was not able to prove that the function is Convex/Concave/Linear. Usually this is because 1) the function is non convex or 2) the function is convex but cannot be proven convex with SUSPECT rule based engine.

Thank you.
